Test package_index

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-on: ["push", "pull_request", "workflow_dispatch"]
+on: [ "push", "pull_request", "workflow_dispatch" ]
 
 jobs:
   build_wheels:
@@ -9,12 +9,12 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        package: ["cadquery-ocp", "lib3mf"]
-        os: ["wasm"] # TODO (fail with missing symbols on native): ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14
-        build_type: ["Release", "Debug"]
+        package: [ "cadquery-ocp", "lib3mf" ]
+        os: [ "wasm" ] # TODO (fail with missing symbols on native): ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14
+        build_type: [ "Release", "Debug" ]
     steps:
       - uses: "actions/checkout@v4"
-      
+
       - uses: "actions/cache@v4"
         id: "cache"
         with:
@@ -27,14 +27,14 @@ jobs:
             cibw-${{ matrix.package }}-${{ matrix.os }}-${{ matrix.build_type }}-${{ github.ref_name }}-
             cibw-${{ matrix.package }}-${{ matrix.os }}-${{ matrix.build_type }}-master-
             cibw-${{ matrix.package }}-${{ matrix.os }}-${{ matrix.build_type }}-
-        
+
       - working-directory: "${{ matrix.package }}"
         run: | # Install all system deps
           pacman -Syu --noconfirm python-pip git
           python -m venv .venv
           . .venv/bin/activate
           pip install $(python -c 'import tomllib; cfg = tomllib.load(open("pyproject.toml", "rb")); print(*cfg["build-system"]["requires"])')
-      
+
       - run: ". .venv/bin/activate && cibuildwheel"
         working-directory: "${{ matrix.package }}"
         env:
@@ -50,7 +50,7 @@ jobs:
         with:
           name: "${{ matrix.package }}-${{ matrix.os }}-${{ matrix.build_type }}"
           path: "${{ matrix.package }}/wheelhouse/*.whl"
-          
+
       - if: "failure()" # Save cache even on failures
         uses: "actions/cache/save@v4"
         with:
@@ -72,8 +72,8 @@ jobs:
             /tmp/cibw-run-*/*-pyodide_wasm32/built_wheel/*
             /tmp/cibw-run-*/*-pyodide_wasm32/repaired_wheel/*
             ${{ matrix.package }}/wheelhouse/*.whl
-          
-  deploy_wheels_to_pages: # keeping old ones
+
+  build_package_index:
     needs: "build_wheels"
     if: "github.ref == 'refs/heads/master'"
     runs-on: "ubuntu-24.04"
@@ -81,27 +81,42 @@ jobs:
       - uses: "actions/checkout@v4"
         with:
           ref: "gh-pages"
-      
-      - uses: "actions/download-artifact@v4"  # Overwrites matching versions
-        with:
-          path: "."
-          
-      - name: "Rebuild index of registry"
-        run: |
-          rm -r cache-* # Cache artifacts are not wanted
-          echo "<!DOCTYPE html><html><head><title>OCP wasm registry</title></head><body><h1>OCP wasm PEP503 registry</h1>" >index.html
-          find . -type f -name "*.whl" | sort -u | while read -r file; do
-            echo "<a href=\"${file#./}\">${file#./}</a><br/>" >>index.html
-          done
-          echo "</body></html>" >>index.html
 
-      - name: "Commit and push"
+      - uses: "actions/download-artifact@v4"
+        with:
+          path: "__wheels__"
+
+      - run: "python __wheels__/generate_package_index.py --wheels . __wheels__ --output ."  # Overwrites matching versions
+
+      - run: "rm -rf __wheels__"
+
+      - uses: "actions/upload-artifact@v4"
+        with:
+          name: "package-index"
+          path: "."
+
+  # TODO: Test build123d integration using the wheels and package index generated above
+
+  deploy_package_index:
+    needs: "build_package_index"
+    if: "github.ref == 'refs/heads/master'"
+    runs-on: "ubuntu-24.04"
+    steps:
+      - uses: "actions/checkout@v4"
+        with:
+          ref: "gh-pages"
+
+      - uses: "actions/download-artifact@v4"
+        with:
+          name: "package-index"
+          path: "."
+
+      - name: "Deploy package index to gh-pages branch"
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add -v .
-          git commit -m "Update wheel registry" || echo "No changes to commit"
+          git add -v index.html
+          git commit -m "Update package index" || echo "No changes to commit"
           git push origin gh-pages
-
 
   # TODO: deploy_wheels_to_pypi: (doesn't support webassembly)
